print("The pictures tell the story")
print("This life has many shades")
print("I’d wake up every morning and before I’d start each day")
print("I’d take a drag from last nights cigarette")
print("That smoldered in it’s tray")
print("Down a little something and then be on my way")
print("I traveled far and wide")
print("And laid this head in many ports")
print("I was guided by a compass")
print("I saw beauty to the north")
print("I drew the tales of many lives")
print("And wore the faces of my own")
print("I had these memories all around me")
print("So I wouldn’t be alone")
print("Some may be from showing up")
print("Others are from growing up")
print("Sometimes I was so messed up and didn’t have a clue")
print("I ain’t winning no one over")
print("I wear it just for you")
print("I’ve got your name written here")
print("In a rose tattoo")
